// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Comment struct {
	CommentID          string     `json:"commentId"`
	PostID             string     `json:"postId"`
	ParentCommentID    *string    `json:"parentCommentId"`
	ChildrenCommentsID []*Comment `json:"childrenCommentsId"`
	Content            string     `json:"content"`
	CreatedAt          time.Time  `json:"createdAt"`
}

type Post struct {
	PostID          string     `json:"postId"`
	Title           string     `json:"title"`
	Content         string     `json:"content"`
	CreatedAt       time.Time  `json:"createdAt"`
	CommentsEnabled bool       `json:"commentsEnabled"`
	Comments        []*Comment `json:"comments"`
}
